export const copy = {
  ko: {
    "meta.title": "다시쓰기 — 분석 프롬프트",
    "nav.home": "수업 홈",
    "nav.brand": "다시쓰기",
    "tool.eyebrow": "조회수보다 중요한 이유",
    "tool.title": "링크를 넣으면, 분석 프롬프트를 복사해요.",
    "tool.lead":
      "AI에게 시킬 일을 정리합니다. 유튜브는 대본을 같이 넣고, 없으면 링크만으로도 프롬프트를 만듭니다.",
    "tool.linkLabel": "공개 영상 링크",
    "tool.linkPlaceholder": "https://www.youtube.com/shorts/",
    "tool.pasteToggle": "대본 붙여넣기",
    "tool.scriptLabel": "대본 (선택)",
    "tool.scriptPlaceholder": "있으면 프롬프트에 함께 넣습니다.",
    "tool.submit": "프롬프트 만들기",
    "tool.hint": "만든 프롬프트를 클로드나 챗GPT에 붙여 넣으면 됩니다.",
    "tool.demo": "예시로 먼저 보기",
    "board.promptTitle": "복사용 프롬프트",
    "board.promptEmpty": "링크를 넣으면 이 자리에 복사용 프롬프트가 생깁니다.",
    "board.copy": "복사하기",
    "board.copied": "복사됨",
    "progress.check": "링크 확인 중",
    "progress.script": "대본 넣는 중",
    "progress.hook": "분석 항목 정리 중",
    "progress.reuse": "프롬프트 만드는 중",
    "err.empty": "영상 링크를 붙여넣어 주세요.",
    "err.unsupported": "유튜브, 쇼츠, 인스타, 틱톡, 페이스북 링크를 넣어 주세요.",
  },
  en: {
    "meta.title": "Rewrite — analysis prompt",
    "nav.home": "Class home",
    "nav.brand": "Rewrite",
    "tool.eyebrow": "More important than views",
    "tool.title": "Paste a link, copy an analysis prompt.",
    "tool.lead":
      "We pack what to ask an AI. YouTube transcripts go in when we can find them. A link alone still works.",
    "tool.linkLabel": "Public video link",
    "tool.linkPlaceholder": "https://www.youtube.com/shorts/",
    "tool.pasteToggle": "Paste a script",
    "tool.scriptLabel": "Script (optional)",
    "tool.scriptPlaceholder": "If you have it, it goes into the prompt.",
    "tool.submit": "Make prompt",
    "tool.hint": "Paste the prompt into Claude or ChatGPT.",
    "tool.demo": "See a sample first",
    "board.promptTitle": "Prompt to copy",
    "board.promptEmpty": "Paste a link and a copyable prompt lands here.",
    "board.copy": "Copy",
    "board.copied": "Copied",
    "progress.check": "Checking the link",
    "progress.script": "Adding the transcript",
    "progress.hook": "Listing what to analyze",
    "progress.reuse": "Building the prompt",
    "err.empty": "Paste a video link first.",
    "err.unsupported": "Use a YouTube, Shorts, Instagram, TikTok, or Facebook link.",
  },
};
