export const en = {
  "meta.title": "Learn vibe coding with a native English speaker",
  "nav.wordmark": "Learn vibe coding with a native English speaker",
  "nav.schedule": "Schedule",
  "nav.reviews": "Reviews",
  "nav.instructor": "Instructor",
  "hero.title": "Learn vibe coding with a native English speaker",
  "hero.promo":
    "You do not need perfect English. You do not need a coding degree. This is 1:1 class, leveled to you — business conversation and your own project.",
  "goal.label": "What is my goal?",
  "goal.placeholder": "Choose a goal",
  "goal.conversation": "I want to get used to native conversation and ask more naturally",
  "goal.business": "I want business English more than everyday small talk",
  "goal.vibe": "I want to learn vibe coding and make it mine",
  "goal.special": "There is a specific vibe-coding topic I want to learn",
  "goal.other": "Other (please write it in the note)",
  "goal.consult": "Get a free class consult",
  "about.title": "In a way that fits your goal!",
  "about.body":
    "Conversational class with a U.S. instructor + 1:1 vibe coding. We are the only ones who do both.",
  "catch.1.kicker": "The front line of AI is in the United States.",
  "catch.1.line": "Overwhelm the pace of tech with English prompts.",
  "catch.2.kicker": "You do not need to know how to code.",
  "catch.2.line": "Talk with AI and build a service of your own.",
  "catch.3.kicker": "1:1 vibe coding with a working U.S. developer in year three.",
  "catch.3.line":
    "Native instinct, no translator. Turn an idea into a working web service at once.",
  "learn.title": "What you take with you",
  "learn.1.title": "A feel for vibe coding",
  "learn.1.body":
    "You leave with the rhythm of building by talking to AI — what to ask, and how to fix it.",
  "learn.2.title": "Working in Cursor",
  "learn.2.body":
    "You use the editor made for vibe coding. After class you can keep building the same way.",
  "learn.3.title": "A project with your name on it",
  "learn.3.body":
    "You are not only watching. After two hours a small project of yours still exists.",
  "tools.title": "Tools we use",
  "tools.caption": "We work in Cursor, and open the AI tools agents actually use.",
  "schedule.title": "Schedule",
  "schedule.lede":
    "Pick a preferred schedule — we confirm it in the consult. First come, first served, so your pick may already be taken.",
  "schedule.pkg.two45": "Two Saturday or Sunday sessions (45 min each)",
  "schedule.pkg.one90": "One 90-minute class",
  "schedule.nightTitle": "Saturday night · KST 22:00–24:00",
  "schedule.sundayTitle": "Sunday morning · KST 08:00–12:00",
  "schedule.pickMany": "Pick at least two times — as many as you like. We lock the final time in the consult.",
  "schedule.tune": "We can adjust around {times}.",
  "schedule.hoursBefore": "I want",
  "schedule.hoursAfter": "sessions.",
  "schedule.mins": "{mins} min",
  "schedule.worth": "about {price} of class",
  "schedule.unavailable": "Taken",
  "schedule.consult": "Get a free consult with this timetable",
  "reviews.title": "Reviews",
  "reviews.1": "Asking questions got easier. Even when I spoke slowly, I felt comfortable.",
  "reviews.1.name": "Student A",
  "reviews.2": "We practiced phrases I can use at work. It was not only everyday chat.",
  "reviews.2.name": "Student B",
  "reviews.3": "I finished a small page in Cursor. This was not a watch-only class.",
  "reviews.3.name": "Student C",
  "instructor.title": "Instructor",
  "instructor.name": "Joseph Starke",
  "instructor.photoAlt": "Portrait of Joseph Starke",
  "instructor.body":
    "A developer based in the United States. He works in Cursor in front of you, and stays with you until the first project is actually shipped.",
  "register.title": "Free class consult",
  "register.lede":
    "Choose a goal and preferred times if you have them. We confirm the schedule in the consult.",
  "register.goal": "My goal",
  "register.timetable": "Timetable",
  "register.name": "Name",
  "register.phone": "Phone number",
  "register.email": "Email",
  "register.kakao": "KakaoTalk ID (optional)",
  "register.contact": "How should we reach you?",
  "register.contactEmail": "Email",
  "register.contactKakao": "KakaoTalk",
  "register.note": "Anything we should know (optional)",
  "register.submit": "Send consult request",
  "register.sending": "Sending…",
  "register.success":
    "Your application was sent. Joseph will write back shortly — please check your inbox.",
  "register.error":
    "Sending failed. If a mail window opened, send that. Or write directly to henzy0625@gmail.com.",
  "footer.email": "henzy0625@gmail.com",
  "footer.credit": "Learn vibe coding with a native English speaker",
};
