export const ko = {
  "meta.title": "미국인과 함께하는 바이브코딩 배우기",
  "nav.wordmark": "미국인과 함께하는 바이브코딩 배우기",
  "nav.schedule": "시간표보기",
  "nav.reviews": "후기",
  "nav.instructor": "강사",
  "hero.title": "미국인과 함께하는 바이브코딩 배우기",
  "hero.promo":
    "영어를 완벽히 구사하지 않아도 됩니다. 코딩을 전공하지 않아도 됩니다. 비지니스 회화를 접해보고, 나만의 프로젝트를 만들기 레벨 맞춤화하여 제공되는 1:1 수업.",
  "goal.label": "나의 목표는?",
  "goal.placeholder": "목표를 골라 주세요",
  "goal.conversation": "원어민회화에 적응하고 더 자연스럽게 질문하고 싶어요",
  "goal.business": "일상회화보다는 비지니스 회화를 늘리고 싶어요",
  "goal.vibe": "바이브코딩을 배워 내것으로 만들고 싶어요",
  "goal.special": "바이브코딩에서 특별히 배우고 싶은 파트가 있어요",
  "goal.other": "기타(하고 싶은 말에 작성해주세요)",
  "goal.consult": "무료수업상담 받기",
  "about.title": "내 목표에 맞는 방식으로!",
  "about.body":
    "미국인 강사와 대화형 수업+ 바이브코딩 1:1 강의는 저희가 유일해요.",
  "catch.1.kicker": "AI의 최전선은 미국에 있습니다.",
  "catch.1.line": "영어 프롬프트로 기술의 속도를 압도하세요.",
  "catch.2.kicker": "코딩을 몰라도 괜찮습니다.",
  "catch.2.line": "AI와 대화하며 나만의 서비스를 만드세요.",
  "catch.3.kicker": "미국 3년차 현직 개발자와 함께 1:1로 진행하는 실전 바이브 코딩.",
  "catch.3.line":
    "번역기를 거치지 않는 네이티브 감각으로, 아이디어를 단숨에 작동하는 웹서비스로 만드세요.",
  "learn.title": "가져가는 것",
  "learn.1.title": "바이브 코딩 감각",
  "learn.1.body":
    "AI와 대화하듯 만드는 리듬이 남습니다. 막혀도 어떻게 물어보고 고칠지 손에 익습니다.",
  "learn.2.title": "Cursor로 일하는 힘",
  "learn.2.body":
    "바이브 코딩에 쓰는 에디터를 직접 다룹니다. 수업이 끝나도 같은 방식으로 계속 만들 수 있습니다.",
  "learn.3.title": "내 이름의 첫 결과물",
  "learn.3.body":
    "구경만 하고 끝나지 않습니다. 두 시간이 지나면 내가 만든 작은 프로젝트가 남아 있습니다.",
  "tools.title": "함께 쓰는 도구",
  "tools.caption": "Cursor를 중심으로, 에이전트 작업에 쓰는 AI를 수업에서 함께 엽니다.",
  "schedule.title": "시간표",
  "schedule.lede":
    "선호하는 스케줄을 선택해주시고 상담때 확정됩니다. 선착순 스케줄 시스템에 따라 선택한 스케줄이 불가능 할 수 있습니다.",
  "schedule.pkg.two45": "토요일 또는 일요일 2회 (45분씩)",
  "schedule.pkg.one90": "1회 90분 수업",
  "schedule.nightTitle": "토요일 밤 · 한국시간 22:00–24:00",
  "schedule.sundayTitle": "일요일 아침 · 한국시간 08:00–12:00",
  "schedule.pickMany": "최소 2개, 원하는 만큼 고르세요. 최종 시간은 상담 후 정해집니다.",
  "schedule.tune": "{times}의 시간에 조율이 가능해요",
  "schedule.hoursBefore": "원하는 수업시수는",
  "schedule.hoursAfter": "회 입니다.",
  "schedule.mins": "{mins}분",
  "schedule.worth": "{price} 상당 수업",
  "schedule.unavailable": "마감",
  "schedule.consult": "이 시간표로 무료 수업 상담받기",
  "reviews.title": "후기",
  "reviews.1": "질문하는 게 덜 어려워졌어요. 말이 느려도 기다려 주셔서 편하게 수업했어요.",
  "reviews.1.name": "수강생 A",
  "reviews.2": "업무에서 바로 쓸 표현을 연습해서 좋았어요. 일상 회화만 반복하지 않아요.",
  "reviews.2.name": "수강생 B",
  "reviews.3": "Cursor로 작은 페이지를 끝까지 만들었어요. 보기만 하는 수업이 아니었어요.",
  "reviews.3.name": "수강생 C",
  "instructor.title": "강사",
  "instructor.name": "Joseph Starke",
  "instructor.photoAlt": "Joseph Starke 프로필 사진",
  "instructor.body":
    "미국에 있는 개발자입니다. Cursor로 직접 만드는 과정을 보여 주며, 여러분이 첫 프로젝트를 끝까지 밀어 보도록 옆에서 돕습니다.",
  "register.title": "무료 수업 상담",
  "register.lede":
    "목표와 선호 시간을 고른 뒤 보내 주세요. 없어도 상담은 가능하고, 시간은 상담 후 확정됩니다.",
  "register.goal": "나의 목표",
  "register.timetable": "시간표",
  "register.name": "이름",
  "register.phone": "전화번호",
  "register.email": "이메일",
  "register.kakao": "카카오톡 아이디 (선택)",
  "register.contact": "연락 받을 방법",
  "register.contactEmail": "이메일",
  "register.contactKakao": "카카오톡",
  "register.note": "하고 싶은 말 (선택)",
  "register.submit": "상담 신청 보내기",
  "register.sending": "보내는 중…",
  "register.success":
    "신청이 전달되었습니다. 조셉이 곧 연락드립니다. 메일함을 확인해 주세요.",
  "register.error":
    "전송에 실패했습니다. 메일 앱이 열리면 그대로 보내 주시거나 henzy0625@gmail.com 으로 직접 연락해 주세요.",
  "footer.email": "henzy0625@gmail.com",
  "footer.credit": "미국인과 함께하는 바이브코딩 배우기",
};
